k9s:
  cluster: minikube
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - all
      - default
      - minikube
  view:
    active: v1/pods default
  featureGates:
    nodeShell: false
  proxy: null
